version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - package_name: mfd
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/theandrew168/mfd
    maintainer: Andrew Dailey <andrew@shallowbrooksoftware.com>
    description: Utility for managing multi-file application deployments
    license: MIT
    formats:
      - deb
